### ISSUE TITLE
Multi-agent system 

### ISSUE THREAD

**Issue by luancaarvalho** [ZhangYiqun018/agent-for-debate#1]
Hello, I read the paper and congratulations on it!

Out of curiosity, how was the multi-agent setup created? Did you use APIs, frameworks, or something else? I didn’t notice this in the paper, so I apologize if I missed it.

Thank you!

**Comment by ZhangYiqun018** [comment]
hello, I have made the code public in the src folder for your reference. Currently, there may be bugs when running the English version. Please feel free to continue communicating with me.

**Comment by luancaarvalho** [comment]
Ty @ZhangYiqun018 !
I will read your code and return with my thoughts
